module.exports = {
	PROGRAM: 'PROGRAM',
	VAR: 'VAR',
	COLON: ':',
	COMMA: ',',
	INTEGER: 'INTEGER',
	REAL: 'REAL',
	INTEGER_CONST: 'INTEGER_CONST',
	REAL_CONST: 'REAL_CONST',
	INTEGER_DIV: 'DIV',
	FLOAT_DIV: '/',
	PLUS: 'PLUS',
	MINUS: 'MINUS',
	MUL: 'MUL',
	DIV: 'DIV',
	LPAREN: '(',
	RPAREN: ')',
	BEGIN: 'BEGIN',
	END: 'END',
	DOT: '.',
	ASSIGN: ':=',
	SEMI: ';',
	ID: 'ID',
	EOF: 'EFO',
};
